version: '3'
services:
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --init_connect='SET collation_connection = utf8_general_ci' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_ROOT_PASSWORD=xmfpffh123*()
      - MYSQL_DATABASE=trello
      - MYSQL_USER=trello
      - MYSQL_PASSWORD=xmfpffh123*()
    healthcheck:
      test: "nc -z localhost 3306"
      interval: 1s
      retries: 120
    ports:
      - "8005:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: