version: '3'
services:
  app:
    image: jwp-trello:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: 1s
      retries: 120
    extra_hosts:
      - "db:10.33.13.62"