version: '3'
services:
  trello-blue:
    image: javajigi/jwp-trello:latest
    restart: always
    ports:
      - "8080"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: 1s
      retries: 120
    extra_hosts:
      - "db:10.33.13.62"
  trello-green:
    image: javajigi/jwp-trello:latest
    restart: always
    ports:
      - "8080"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: 1s
      retries: 120
    extra_hosts:
      - "db:10.33.13.62"